export const MODEL_PROVIDERS: Record<string, string> = {
  'claude-sonnet-4': 'Anthropic',
  'claude-4-sonnet': 'Anthropic',
  'claude-opus-4': 'Anthropic',
  'claude-3.7-sonnet': 'Anthropic',
  'claude-3.5-sonnet': 'Anthropic',
  'claude-3.5-haiku': 'Anthropic',
  'gpt-4.1': 'OpenAI',
  'gpt-4.1-mini': 'OpenAI',
  'gpt-4o': 'OpenAI',
  'gpt-4o-mini': 'OpenAI',
  'o4': 'OpenAI',
  'o4-mini': 'OpenAI',
  'gemini-2.5-flash': 'Google',
  'gemini-2.5-pro': 'Google',
  'gemini-2.0-flash': 'Google',
  'deepseek-r1': 'DeepSeek',
  'deepseek-v3': 'DeepSeek',
  'deepseek-coder': 'DeepSeek',
} 